# Generated by Django 6.0.7 on 2026-07-09 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('BK', 'Bank'), ('CA', 'Cash'), ('WL', 'Wallet'), ('CC', 'Credit Card')], max_length=2)),
                ('currency', models.CharField(choices=[('IRR', 'Iranian Rial'), ('USD', 'US Dollar')], default='IRR', max_length=3)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account_status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('EX', 'Expense'), ('SP', 'Spend')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
