# Generated by Django 6.0.7 on 2026-07-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], max_length=10),
        ),
    ]
